# Generated by Django 5.1.3 on 2024-12-01 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('series', models.CharField(max_length=255)),
                ('set_number', models.CharField(max_length=20)),
                ('rarity', models.CharField(blank=True, max_length=100, null=True)),
                ('types', models.JSONField(blank=True, null=True)),
                ('market_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_small_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_large_url', models.URLField(blank=True, max_length=500, null=True)),
                ('tcgplayer_url', models.URLField(blank=True, max_length=500, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='sets.userset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
