# Generated by Django 5.1.3 on 2024-12-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='variant_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('holofoil', 'Holofoil'), ('reverseHolofoil', 'Reverse Holofoil')], max_length=50),
        ),
    ]
