# Generated by Django 5.1.3 on 2024-12-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercard',
            name='image_large_url',
        ),
        migrations.RemoveField(
            model_name='usercard',
            name='image_small_url',
        ),
        migrations.RemoveField(
            model_name='usercard',
            name='market_price',
        ),
        migrations.RemoveField(
            model_name='usercard',
            name='tcgplayer_url',
        ),
        migrations.AlterField(
            model_name='usercard',
            name='card_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
