# Generated by Django 5.1.3 on 2024-12-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_usercard_image_large_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
