# Generated by Django 5.1.3 on 2024-12-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_usercard_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='market_price_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
