# Generated by Django 5.1.3 on 2024-12-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_usercard_variant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
