# Generated by Django 5.1.3 on 2024-12-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userset',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='userset',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='userset',
            name='symbol_url',
        ),
        migrations.RemoveField(
            model_name='userset',
            name='updated_at',
        ),
    ]
