# Generated by Django 5.1.3 on 2024-12-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0003_userset_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userset',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
